# https://blowfish.page/docs/getting-started/

# TODO: change favicon
# TODO: tweak bg color
# TODO: buy domain
# TODO: index in google
# TODO: ensure good lighthouse score
# TODO: add README.md
# TODO: think about "Powered by Hugo & Blowfish" in footer

theme = "blowfish"  # UNCOMMENT THIS LINE
defaultContentLanguage = "en"
# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles
baseURL = "https://bpetrukovich.com/"
enableRobotsTXT = true
summaryLength = 0
buildDrafts = false
buildFuture = false
enableEmoji = true

# TODO: add googleAnalytics
#  googleAnalytics = "G-XXXXXXXXX"

[pagination]
pagerSize = 100

[imaging]
anchor = "Center"

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]

[related]
threshold = 0
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name = "series"
weight = 50

[[related.indices]]
name = "authors"
weight = 20

[[related.indices]]
name = "date"
weight = 10

[[related.indices]]
applyFilter = false
name = "fragmentrefs"
type = "fragments"
weight = 10

[params.author]
# TODO: think about adding a photo
name = "Bogdan Petrukovich"
# TODO: add textdecoration to links
# TODO: add subtitle
headline = "Fullstack dev at <a href=\"https://www.itransition.com/\" target=\"_blank\" rel=\"noopener noreferrer\">itransition</a> · student at <a href=\"https://www.bsuir.by/en/\" target=\"_blank\" rel=\"noopener noreferrer\">BSUIR</a>"
bio = "Obsessed with learning and building every day"
links = [
  { github = "https://github.com/bpetrukovich" },
  { linkedin = "https://linkedin.com/in/bpetrukovich" }
]
