disabled = false
languageCode = "ru"
languageName = "Русский"
weight = 2
title = "bpetrukovich"

[params]
displayName = "RU"
isoCode = "ru"
rtl = false
dateFormat = "2 Января 2006"
description = "Я Богдан Петрукович, fullstack dev в itransition и студент BSUIR. Добро пожаловать на мой минималистичный и всегда актуальный персональный сайт."
